interval: 30
timeout: 2
name: nas
docker_exec: /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker
#websocket: true
#async_mode: eventlet
allowed_commands: ['ps', 'df', 'top']
services:
- name: '@docker:baidupan'